// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deadline } from "./Deadline";
import type { PomodoroInterruption } from "./PomodoroInterruption";
import type { PomodoroSession } from "./PomodoroSession";
import type { SettingKV } from "./SettingKV";
import type { Task } from "./Task";

export type AppData = { 
/**
 * 备份结构版本。导出时写入当前版本；导入旧文件时默认 1。
 * camelCase 别名让前端 `schemaVersion` 直接对应。
 */
schemaVersion: number, tasks: Array<Task>, deadlines: Array<Deadline>, 
/**
 * 专注记录。`None`（早期 v1 备份只导出 tasks/deadlines，没有此字段）=
 * 保留库中现有记录不动；`Some` = 整体替换。此前是必填 Vec，前端迁移把缺失
 * 补成 `[]`，恢复一份合法的旧备份就会把用户全部专注历史清空。
 */
sessions?: Array<PomodoroSession> | null, 
/**
 * Optional so backups written by older builds (without this field) still
 * import cleanly; absent simply means "restore nothing".
 */
settings: Array<SettingKV>, 
/**
 * v2 可选扩展：专注中断记录。`None`（旧备份无此字段）= 保留库中现有
 * 记录不动；`Some` = 整体替换。避免恢复旧备份时误删现有中断数据。
 */
interruptions?: Array<PomodoroInterruption> | null, };
