// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioSourceStatus = { 
/**
 * loopback（播放环回）/ capture（麦克风）。
 */
kind: string, 
/**
 * 本轮开流是否成功。
 */
ok: boolean, };
