// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioSourceStatus } from "./AudioSourceStatus";

/**
 * audio:status 事件载荷（W-审计：采集管线健康态 + 当前活动口径）。
 * 只在开流结果变化时发射（换代重拉 / 设备恢复 / 降级），频率极低。
 * - 前端状态行据 `sources` 展示「麦克风不可用」等真实口径（此前降级只有
 *   log::warn，UI 仍宣称麦克风频谱）；
 * - `mode`/`dist` 是**进程级单管线**的当前参数：多屏窗口配置不一致时后启动
 *   者全局生效，其余窗口据此前缀「跟随全局」提示（的 UI 侧补丁）。
 */
export type AudioStatusPayload = { 
/**
 * 管线当前检测模式：playback / microphone / both。
 */
mode: string, 
/**
 * 管线当前频带分布：log / linear。
 */
dist: string, 
/**
 * 各采集源健康态（按启动参数 kinds 顺序，含打开失败的源）。
 */
sources: Array<AudioSourceStatus>, };
