// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatteryInfo = { present: boolean, percent: number, charging: boolean, 
/**
 * 预计剩余时间（秒，放电时的 BatteryLifeTime）。0 = 未知或交流供电
 * （系统对 0xFFFFFFFF「未知」与本模块的「0」约定统一为不可用即 0，
 * 前端据此隐藏剩余时间，绝不显示编造的估计值）。
 */
secs_left: number, };
