// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CLIP（剪贴板历史）：一条剪贴板留档。`kind` = "text" | "image"（未知值
 * 回落 text）。`hash`（去重键）与 `expires_at` 只存在于 DB 内部，不经 IPC
 * 暴露；`preview` 由 Rust 侧生成（首个非空行压缩空白后截断），前端列表
 * 直接展示，全文/图片引用按需取用。
 */
export type ClipboardEntry = { id: string, 
/**
 * "text" | "image" | "files"。
 */
kind: string, 
/**
 * 单行摘要：文本条目为内容首行；图片条目为空串（前端用本地化文案 +
 * 像素尺寸渲染）；文件条目为文件名列表（逗号分隔）。
 */
preview: string, 
/**
 * 文本条目的全文（图片条目为 None）。`list` 命令不下发全文（每行至多
 * 512KB × 200+ 行全量过 IPC 太重），该路径下为 None，全文经
 * `get_clipboard_entry` 按需取。
 */
text: string | null, 
/**
 * 文本条目的行数（列表「{n} 行」元信息；list 路径由 SQL 现算）。非文本行为 0。
 */
text_lines: number, 
/**
 * 图片条目的文件名（clip 数据目录内，非完整路径；文本条目为 None）。
 */
image_file: string | null, 
/**
 * 图片条目的像素宽（文本条目为 None）。
 */
image_w: number | null, 
/**
 * 图片条目的像素高（文本条目为 None）。
 */
image_h: number | null, 
/**
 * 图片条目的 PNG 字节数（文本条目为 0）。
 */
image_bytes: number, 
/**
 * 文件条目的完整路径列表（JSON 数组字符串；v10 迁移列，其余条目 None）。
 * 前端按 JSON.parse 消费（数组元素为绝对路径字符串）。
 */
files: string | null, 
/**
 * 来源进程名（设置默认关闭；开启后为复制时前台窗口进程的可执行文件名）。
 */
source_app: string | null, 
/**
 * 置顶标记：置顶条目排在列表最前，且不参与 LRU / 过期清理。
 */
pinned: boolean, 
/**
 * UTC 毫秒精度 Z 字符串（与库内其余时间戳口径一致）。
 */
created_at: string, };
