// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipboardEntry } from "./ClipboardEntry";

/**
 * 点击条目回写系统剪贴板（文本 = CF_UNICODETEXT；图片 = DIBV5+DIB 双格式；
 * 文件 = 重建 CF_HDROP）。
 * 先 touch 置顶再写剪贴板：随后 WM_CLIPBOARDUPDATE 捕获到同内容时会命中
 * 「与最新一条相同 → 刷新」去重路径，不产生重复行。这是刻意的顺序——若先
 * 写后 touch，捕获线程可能赶在 touch 落库前读到库，把回写内容当新条目插出
 * 重复行；代价是写剪贴板失败时该条已被顶到最前（接受：失败本就罕见，顺序
 * 抖动无害于数据）。
 */
export type ClipboardRestoreOutcome = { entry: ClipboardEntry, 
/**
 * 文件条目回写时因源路径已不存在而被跳过的文件数（其余条目为 0）——
 * 前端据此提示「部分文件已不存在」。JSON 序列化为 number（与
 * ClipboardEntry.image_bytes 同款覆盖，避免 ts-rs 默认映射成 bigint）。
 */
skipped_missing: number, };
