// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 关闭全部窗口 · 第一段：枚举候选并回报数量与标题样本（不执行）。
 */
export type CloseAllSummary = { count: number, 
/**
 * 最多 5 条标题样本（确认对话框展示用）。
 */
samples: Array<string>, 
/**
 * 候选窗口句柄（第二段执行时重新校验，防第一段后窗口已自关/换主）。
 */
handles: number[], };
