// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A-4：SQLite 聚合口径的按日专注统计。由 `aggregate_sessions` 命令返回，
 * 让前端在超大数据集（>500 段会话）下仍能得到全量累计/年度热图，而不受内存
 * SESSIONS_CAP 截断影响。`date` 为本地日历日（YYYY-MM-DD），与前端 `toDateKey`
 * 的本地口径一致；`focus_seconds` 为该日专注秒数合计，`focus_count` 为轮数。
 */
export type DailyFocusStat = { date: string, focus_seconds: number, focus_count: number, };
