// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiskInfo = { name: string, mount: string, total_gb: number, used_gb: number, percent: number, };
