// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 文件哈希结果（hex 小写）。bytes 用于组件展示体积。
 */
export type FileHashes = { md5: string, sha1: string, sha256: string, sha512: string, bytes: number, };
