// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyFocusStat } from "./DailyFocusStat";

/**
 * `aggregate_sessions` 的返回体，全量专注历史按本地日历日聚合。
 */
export type FocusAggregate = { daily: Array<DailyFocusStat>, };
