// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 24 小时时段分布的一格。`hour` 为本地小时（0-23），
 * `focus_seconds` 为该小时分摊到的专注秒数（跨小时段按墙钟占比切分），
 * `focus_count` 为结束时刻落在本小时的会话数（含未完成段）。
 */
export type HourlyFocusStat = { hour: number, focus_seconds: number, focus_count: number, };
