// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * W-131 媒体监控行为偏好快照（前端回显）。
 */
export type MediaBehavior = { pauseOthers: boolean, blockedSessions: Array<string>, };
