// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个可选媒体会话（应用）的描述。
 */
export type MediaSessionInfo = { 
/**
 * SourceAppUserModelId，选择时回传。
 */
id: string, 
/**
 * 应用名：取 AUMID 最后一段（`SpotifyAB.Spotify…!Spotify` → `Spotify`）。
 */
name: string, playing: boolean, 
/**
 * 已被列入黑名单（选择器里进「已隐藏」区，点击恢复）。
 */
blocked: boolean, };
