// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkInfo = { name: string, 
/**
 * Bytes per second (raw `sysinfo` counter). The frontend formats to
 * B/s / KB/s / MB/s; it must NOT be misread as kbit/s.
 */
rx_bps: number, tx_bps: number, 
/**
 * 开机以来累计收发字节（sysinfo 绝对计数器，跨采样帧单调递增；
 * 网卡重置时归零重来，前端仅作展示不作差分）。
 */
total_received: number, total_transmitted: number, 
/**
 * 连接状态：true = 本帧在 sysinfo 列表中（sysinfo 会过滤掉媒体
 * 断开的网卡）；false = 刚断开的幽灵行（保留 `NET_GHOST_FRAMES` 帧）。
 */
up: boolean, };
