// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DOCK（通知中心）：一条已留档的自发通知历史。`kind` 决定通知中心里的
 * 左侧色条（pomodoro / todo / info）。`expires_at` 是行级过期锚点，只存在于
 * DB 内部，不经 IPC 暴露。
 */
export type NotificationRecord = { id: string, 
/**
 * 来源标识（settings-store NotificationSource 或 pomodoro/todo 内核事件）。
 */
source: string, title: string, body: string, kind: string, read: boolean, 
/**
 * UTC 毫秒精度 Z 字符串（与库内其余时间戳口径一致）。
 */
created_at: string, };
