// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `files:classify_path` 返回（快捷方式小组件拖入识别）：显示名（去扩展名）
 * 与类别（url / folder / file）。
 */
export type PathKind = { label: string, kind: string, 
/**
 * `.lnk`/`.url` 解析出的目标路径（非快捷方式为 None）。前端应存它而非
 * 原路径——桌面上的快捷方式被删后，入口指向的目标仍然可用。
 */
path?: string, };
