// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PomodoroInterruption = { id: string, started_at: string, ended_at: string, reason: string, mode: string, elapsed_seconds: number, };
