// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `process-event` 事件载荷（emit 至 widget-0）。
 */
export type ProcessEvent = { 
/**
 * 触发的规则模式原文（前端规则匹配键）。
 */
pattern: string, 
/**
 * 具体进程名（如 cargo.exe）。
 */
name: string, 
/**
 * "start" | "exit"。
 */
kind: string, };
