// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * （打断统计 SQL 全量化）：`monthly_interruption_breakdown` 的返回体——
 * 某虚拟日历月内各中断原因的次数，突破前端 INTERRUPTIONS_CAP=300 截断。
 */
export type ReasonCount = { reason: string, count: number, };
