// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single key/value row from the settings table (included in full backups so
 * widget layouts, app prefs and the localStorage mirror survive restores).
 */
export type SettingKV = { key: string, value: string, };
