// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次待处理的冻结帧元数据（snip 窗口就绪后向前端提供）。
 */
export type SnipFrame = { 
/**
 * PNG 落盘路径（<appdata>/snip/ 下）。
 */
path: string, 
/**
 * 物理像素宽高。
 */
phys_w: number, phys_h: number, 
/**
 * 显示器缩放（物理 → 逻辑 CSS 像素换算）。
 */
scale: number, };
