// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskbarRule } from "./TaskbarRule";

/**
 * 可带规则的两个状态各自的规则表（§4 rules）。
 */
export type TaskbarRules = { visibleWindow: Array<TaskbarRule>, maximizedWindow: Array<TaskbarRule>, };
