// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskbarStateKey } from "./TaskbarStateKey";

/**
 * `taskbar:state-changed` 负载：某显示器当前生效状态变化，
 * 仅变化时 emit（Rust 侧合并防抖 ≤200ms）。
 */
export type TaskbarStateChanged = { activeState: TaskbarStateKey, 
/**
 * 显示器稳定槽位（monitor.rs `monitor:slots`，与 widget-N 同号）。
 */
monitor: number, 
/**
 * 命中规则 id（仅 visibleWindow / maximizedWindow 走规则时非空）。
 */
matchedRule: string | null, };
