// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskbarAppearance } from "./TaskbarAppearance";
import type { TaskbarMatchType } from "./TaskbarMatchType";

/**
 * 一条窗口规则（§4 TaskbarRule）。`inactive_appearance` 仅在命中窗口
 * 非前台时使用。
 */
export type TaskbarRule = { id: string, matchType: TaskbarMatchType, pattern: string, appearance: TaskbarAppearance, inactiveAppearance?: TaskbarAppearance, };
