// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskbarAccent } from "./TaskbarAccent";

/**
 * 单套外观（§4 TaskbarAppearance）。颜色统一 `#rrggbbaa` 存储（3/4/6 位
 * 输入由 [`normalize_hex_color`] 归一，坏值回默认）；`blur_radius` 0–750，
 * 越界回默认 30（回退而非钳制，与前端 numOr 语义一致）。
 */
export type TaskbarAppearance = { accent: TaskbarAccent, color: string, showPeek: boolean, showLine: boolean, blurRadius: number, };
