// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * accent 五值（§1.1 表）。`normal` = 恢复系统默认外观。
 */
export type TaskbarAccent = "normal" | "opaque" | "clear" | "blur" | "acrylic";
