// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskbarPhase } from "./TaskbarPhase";
import type { TaskbarType } from "./TaskbarType";

/**
 * `taskbar:status` 负载 / `get_taskbar_status` 返回体（F-10 状态条）。
 */
export type TaskbarStatus = { phase: TaskbarPhase, 
/**
 * Failed / Degraded 时的一句话原因与建议（如「需要重启资源管理器」）。
 */
reason: string | null, 
/**
 * 稳定机器码（不随文案变化），前端据此挂接专属动作（如
 * `stale_dll_resident` → 一键 / 自动重启资源管理器完成 DLL 升级）。
 */
code: string | null, taskbarType: TaskbarType, 
/**
 * 主进程管道协议版本（protocol.rs PROTOCOL_VERSION），诊断信息用。
 */
protocolVersion: number, };
