// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 忽略窗口三组列表（§4 ignoredWindows；IsFiltered 语义）。
 */
export type TaskbarIgnoredWindows = { classes: Array<string>, titles: Array<string>, processes: Array<string>, };
