// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * （任务用时归集 SQL 全量化）：`task_focus_breakdown` 的返回体——按
 * 专注事件聚合的已完成段秒数与段数（task_id / event_label 均为 NULL 的
 * 行即「未关联」组），突破前端 SESSIONS_CAP=500 内存截断。秒数由前端
 * 出口一次取整为分钟。
 */
export type TaskFocusStat = { task_id: string | null, event_label: string | null, focus_seconds: number, sessions: number, };
