// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskbarIgnoredWindows } from "./TaskbarIgnoredWindows";
import type { TaskbarOverride } from "./TaskbarOverride";
import type { TaskbarRules } from "./TaskbarRules";
import type { TaskbarStates } from "./TaskbarStates";

/**
 * 任务栏配置根（§4 TaskbarSettings）。`Deserialize` 为**容错实现**
 * （[`TaskbarSettings::from_json_value`]）：缺字段 / 坏颜色 / 越界半径 /
 * 未知枚举一律回默认，解析永不失败（仿 parse_clip_config 防御风格）。
 */
export type TaskbarSettings = { 
/**
 * 总开关（D1：默认 false，新功能默认关，F-1）。
 */
enabled: boolean, states: TaskbarStates, rules: TaskbarRules, ignoredWindows: TaskbarIgnoredWindows, 
/**
 * 逐显示器独立配置（P2，F-6；默认 false）。
 */
perMonitor: boolean, monitorOverrides: { [key in string]: TaskbarOverride }, };
