// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Task = { id: string, title: string, completed: boolean, created_at: string, 
/**
 * 截止时间（ISO 字符串；空 = 无截止）。旧备份缺省为空。
 */
due_at: string, 
/**
 * 优先级：0 无 / 1 低 / 2 中 / 3 高。
 */
priority: number, 
/**
 * 标签（JSON 数组字符串，如 `["工作"]`）。
 */
tags: string, 
/**
 * 手动排序权重（小的在前）。
 */
sort_order: number, };
