// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskbarIgnoredWindows } from "./TaskbarIgnoredWindows";
import type { TaskbarRules } from "./TaskbarRules";
import type { TaskbarStates } from "./TaskbarStates";

/**
 * 单显示器覆盖（§4 `Partial<TaskbarSettings>`：仅顶层可选，值为整体
 * 替换，不深合并）。由设置页消费。
 */
export type TaskbarOverride = { enabled?: boolean, states?: TaskbarStates, rules?: TaskbarRules, ignoredWindows?: TaskbarIgnoredWindows, perMonitor?: boolean, };
