// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 七态键（§4 TaskbarStateKey）。事件负载中的 `activeState` 即此类型。
 */
export type TaskbarStateKey = "desktop" | "visibleWindow" | "maximizedWindow" | "startOpened" | "searchOpened" | "taskViewOpened" | "batterySaver";
