// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 实现路径（F-12）：`xaml` = TAP 注入（22621+）；`swca` = 路径 A（Mixed，
 * P3）；`none` = 此系统版本暂不支持。
 */
export type TaskbarPath = "xaml" | "swca" | "none";
