// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskbarStateAppearance } from "./TaskbarStateAppearance";

/**
 * 七态配置表（§4 `states: Record<TaskbarStateKey, ...>` 的结构化形式，
 * 线协议形状一致：键 camelCase）。
 */
export type TaskbarStates = { desktop: TaskbarStateAppearance, visibleWindow: TaskbarStateAppearance, maximizedWindow: TaskbarStateAppearance, startOpened: TaskbarStateAppearance, searchOpened: TaskbarStateAppearance, taskViewOpened: TaskbarStateAppearance, batterySaver: TaskbarStateAppearance, };
