// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 规则匹配语义：
 * `Class` 精确（大小写敏感）/ `Process` 可执行文件名大小写不敏感精确 /
 * `Title` 子串包含（大小写敏感）。**空 pattern 恒不匹配**——标杆的空
 * title pattern 会命中一切，属脚本事故面，此处收紧并两侧一致。
 */
export type TaskbarMatchType = "class" | "title" | "process";
