// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 注入状态机 phase（F-10）：`Idle → Injecting → Ready / Failed / Degraded`。
 */
export type TaskbarPhase = "idle" | "injecting" | "ready" | "failed" | "degraded";
