// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 流量汇总（今日 + 本月）。今日值来自记录器内存（权威、含未落库增量），
 * 本月值 = 库内当月其余天数之和 + 今日内存值。
 */
export type TrafficSummary = { 
/**
 * 本地日期 "YYYY-MM-DD"。
 */
day: string, today_rx: number, today_tx: number, month_rx: number, month_tx: number, };
