// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateInfo = { current_version: string, latest_version: string, has_update: boolean, notes: string, };
