// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * velatap.dll 完整性诊断——分发 DLL 与已解包副本的 SHA-256，供设置页
 * 诊断区展示并与发布侧 SHA256SUMS 人工比对（安装包未签名期间的用户侧
 * 校验通道）。运行时注入链另有 §5.4 的解包哈希校验，此处只读不判定。
 */
export type VelatapDigest = { bundled_path: string | null, bundled_sha256: string | null, unpacked_path: string | null, unpacked_sha256: string | null, unpacked_matches_bundled: boolean, };
