// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WallpaperPalette } from "./WallpaperPalette";

/**
 * §4.4 壁纸取色快照：`path` + `mtime_ms` 即缓存键（同键不重算，前端亦可据此
 * 判断"壁纸未变"），随 `get_wallpaper_palette` 返回与 `wallpaper:changed` 事件下发。
 */
export type WallpaperPaletteInfo = { path: string, mtime_ms: number, palette: WallpaperPalette, };
