// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §4.4 壁纸取色三色（`#rrggbb`）：主色 / 次色（色相与主色差 ≥30°，单色壁纸
 * 无次色）/ 中性基调色（全图均值）。均为原始候选（主题已不从壁纸派生颜色，
 * 该快照用于样式页「壁纸」区展示与当前壁纸标识）。
 */
export type WallpaperPalette = { primary: string, secondary: string | null, neutral: string, };
